### ISSUE TITLE
univalue.h not found error

### ISSUE THREAD

**Issue by namanyayg** [bloq/cpptrade#2]
Errors on `make`. `bitcoin` (no wallet) is installed.

```
Util.cc:13:22: fatal error: univalue.h: No such file or directory
 #include <univalue.h>
                      ^
compilation terminated.
Makefile:703: recipe for target 'Util.o' failed
make[1]: *** [Util.o] Error 1
make[1]: Leaving directory '/root/cpptrade'
Makefile:577: recipe for target 'all' failed
make: *** [all] Error 2
root@localhost:~/cpptrade# make check
g++ -DHAVE_CONFIG_H -I.  -std=c++11 -pthread -I./vendor/liquibook/src   -O2 -Wall -g -I/usr/local/include/evhtp -MT Util.o -MD -MP -MF .deps/Util.Tpo -c -o Util.o Util.cc
Util.cc:13:22: fatal error: univalue.h: No such file or directory
 #include <univalue.h>
                      ^
compilation terminated.
Makefile:703: recipe for target 'Util.o' failed
make: *** [Util.o] Error 1
```

**Comment by jgarzik** [comment]
This means the build system must have https://github.com/jgarzik/univalue/ installed on the system and available to `configure` script.

**Comment by namanyayg** [comment]
Thank you!

**Comment by nirajrussspacetech** [comment]
Even after installing univalue. 'm getting this error. Kindly hep

g++  -O2 -g -Wall -I/home/uss/Work/Trade_Server/libevhtp-develop/build/include -I/home/uss/Work/Trade_Server/libevhtp-develop/include -pthread   -o obsrv srvapi.o obsrv.o Market.o Order.o HttpUtil.o libobcommon.a  -levhtp -lunivalue -levent_core -levent_openssl -lssl -lcrypto  -luuid  
/usr/bin/x86_64-linux-gnu-ld: cannot find -lunivalue

**Comment by jgarzik** [comment]
~~Need to add `-L/usr/local/some/directory` to find where libunivalue is installed~~

Sounds like you got it.
