### ISSUE TITLE
Issue on mac os x 10.10.5

### ISSUE THREAD

**Issue by mandys** [bloq/cpptrade#4]
When I try make, I get the following

In file included from ./vendor/liquibook/src/book/depth_order_book.h:6:
./vendor/liquibook/src/book/order_book.h:481:8: warning: unused variable 'price_change' [-Wunused-variable]
  bool price_change = new_price && (new_price != order->price());
       ^
In file included from obsrv.cc:24:
./srv.h:37:3: warning: 'SHA256_Init' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
                SHA256_Init(&bodyHash);
                ^
/usr/include/openssl/sha.h:147:5: note: 'SHA256_Init' has been explicitly marked deprecated here
int SHA256_Init(SHA256_CTX *c) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
    ^
obsrv.cc:79:28: error: use of undeclared identifier 'htparser_get_methodstr_m'; did you mean 'htparser_get_methodstr'?
        const char *method_name = htparser_get_methodstr_m(method);
                                  ^~~~~~~~~~~~~~~~~~~~~~~~
                                  htparser_get_methodstr
./htparse.h:93:16: note: 'htparser_get_methodstr' declared here
const char   * htparser_get_methodstr(htparser *);
               ^
obsrv.cc:79:53: error: cannot initialize a parameter of type 'htparser *' with an lvalue of type 'htp_method'
        const char *method_name = htparser_get_methodstr_m(method);
                                                           ^~~~~~
./htparse.h:93:49: note: passing argument to parameter here
const char   * htparser_get_methodstr(htparser *);
                                                ^
obsrv.cc:107:2: warning: 'SHA256_Update' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
        SHA256_Update(&state->bodyHash, chunk, bufsz);
        ^
/usr/include/openssl/sha.h:148:5: note: 'SHA256_Update' has been explicitly marked deprecated here
int SHA256_Update(SHA256_CTX *c, const void *data, size_t len) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
    ^
obsrv.cc:153:72: error: expected ')'
        evhtp_request_set_hook (req, evhtp_hook_on_request_fini, (evhtp_hook) req_finish_cb, state);
                                                                              ^

**Comment by jgarzik** [comment]
This is an ssl library installation issue, not a cpptrade issue.

`brew` probably has an updated openssl library you can use.
